(defun path(x e cur)
    (cond
        ((AND (atom x) (eq x e)) cur)
        ((atom x) nil)
        (t (apply 'append (mapcar (lambda (el) 
                        (path el e (append cur (list (car x)))))
                                                x)))
    )
)

(write (path '(a (b (g)) (c (d (e)) (f))) 'e nil))
(format t "~%")
(write (path '(a (b (g)) (c (d (e)) (f))) 'v nil))
(format t "~%")
(write (path '(a (b (g)) (c (d (e)) (f))) 'f nil))
(format t "~%")
(write (path '(a (b (g)) (c (d (e)) (f))) 'b nil))
(format t "~%")
(write (path '(a (b (g)) (c (d (e)) (f))) 'v nil))
(format t "~%")